//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessMastertoRoleMap
    {
        public int ID { get; set; }
        public int ProcessMaster_ID { get; set; }
        public int RoleID { get; set; }
    }
}
