//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Process_Master
    {
        public int ID { get; set; }
        public string ProcessName { get; set; }
        public string ProcessDesc { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> creationTime { get; set; }
        public string deactivateBy { get; set; }
        public Nullable<System.DateTime> deactivatonTime { get; set; }
        public bool IsActive { get; set; }
    }
}
