//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Document_List
    {
        public int ID { get; set; }
        public string BR_ID { get; set; }
        public string Docname { get; set; }
        public string Doctype { get; set; }
        public string DocFilePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string[] DoctypeArr { get; set; }
    }
}
