//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Action_Master
    {
        public int ID { get; set; }
        public string ActionName { get; set; }
        public string ActionDesc { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> creationTime { get; set; }
        public string deactivateBy { get; set; }
        public Nullable<System.DateTime> deactivatonTime { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Process_ID { get; set; }
        public Nullable<int> NextAction { get; set; }
        public Nullable<int> Role_ID { get; set; }
    }
}
