//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Role_Master
    {
        public int ID { get; set; }
        public string RoleName { get; set; }
        public string RoleDesc { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Time { get; set; }
        public bool Status { get; set; }
        public string Deactivated_By { get; set; }
        public System.DateTime Deactivated_Time { get; set; }
    }
}
