//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Birth_Process_Action
    {
        public int ID { get; set; }
        public int B_ID { get; set; }
        public string Comments { get; set; }
        public string Action { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> U_ID { get; set; }
    }
}
