//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DocumentsAttachment
    {
        public int ID { get; set; }
        public string DocumentTypeName { get; set; }
        public string DocumentType { get; set; }
        public string DocumentPath { get; set; }
        public string ProcessId { get; set; }
        public string ProcessID { get; set; }
    }
}
