//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DeathRegistration
    {
        public int ID { get; set; }
        public string Name_of_Informant { get; set; }
        public string Name_of_Deceased_Person { get; set; }
        public string Gender_Of_Deceased_Person { get; set; }
        public string Name_of_Deceased_FatherHusband { get; set; }
        public Nullable<System.DateTime> Date_Of_Death { get; set; }
        public string Place_Of_Death { get; set; }
        public string Age_Of_Deceased { get; set; }
        public string Address { get; set; }
        public string Gram_Panchayat_Unit { get; set; }
        public string Nationality { get; set; }
        public string DocumentName { get; set; }
        public string DocumentBytes { get; set; }
        public string DocumentType { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
