//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Customer_Master
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PAN { get; set; }
        public string DrivingLicenseNo { get; set; }
        public string IDProofeNumber { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string Dist { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> Mob_no { get; set; }
        public Nullable<int> LandlineNo { get; set; }
        public string EmailID { get; set; }
        public string OtherGovID { get; set; }
        public string CINNo { get; set; }
        public string GISTNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modifiy_Date { get; set; }
        public string Cust_Id { get; set; }
        public string IDProofe { get; set; }
        public string Nationality { get; set; }
        public string OrganisationName { get; set; }
        public string OrganisationType { get; set; }
        public string AutherizedPerson { get; set; }
        public string AutherizPrsDesig { get; set; }
        public string AutherizPrsEmail_Id { get; set; }
        public Nullable<int> AutherizPrsMobile_No { get; set; }
        public string City { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string CustType { get; set; }
        public string IdProofeNumber { get; set; }
        public string AutherizedPersonName { get; set; }
        public string Organisation_Certificate { get; set; }
        public string Organisation_Certificate_No { get; set; }
        public string HouseNo { get; set; }
        public string Locality { get; set; }
        public string Document_FileName { get; set; }
        public string Identity_file_Bytes { get; set; }
    }
}
