//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MNServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_audit
    {
        public int id { get; set; }
        public string page_name { get; set; }
        public string user_name { get; set; }
        public string ip_address { get; set; }
        public string time_stamp { get; set; }
        public string session_id { get; set; }
        public Nullable<bool> authenticate { get; set; }
    }
}
